/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.JTable;

/**
 *
 * @author novil
 */
public class BillingPanel extends javax.swing.JPanel {

    /**
     * Creates new form Billing
     */
    public BillingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billingDateUntilLabel = new javax.swing.JLabel();
        billingNameTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        billingsTable = new javax.swing.JTable();
        addBillingButton = new javax.swing.JButton();
        deleteBillingButton = new javax.swing.JButton();
        billingComputerLabel = new javax.swing.JLabel();
        billingComputerComboBox = new javax.swing.JTextField();
        billingFromDateTextField = new javax.swing.JTextField();
        billingDateFromLabel = new javax.swing.JLabel();
        billingUsernameTextField4 = new javax.swing.JTextField();
        billingNameLabel = new javax.swing.JLabel();

        billingDateUntilLabel.setText("Sampai Tanggal");

        billingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal Dari", "Tanggal Sampai", "Nama", "Operator", "Komputer"
            }
        ));
        jScrollPane3.setViewportView(billingsTable);

        addBillingButton.setText("Tambah");
        addBillingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBillingButtonActionPerformed(evt);
            }
        });

        deleteBillingButton.setText("Hapus");
        deleteBillingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBillingButtonActionPerformed(evt);
            }
        });

        billingComputerLabel.setText("Komputer");

        billingDateFromLabel.setText("Dari Tanggal");

        billingNameLabel.setText("Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBillingButton)
                        .addGap(10, 10, 10)
                        .addComponent(deleteBillingButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(billingNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(billingNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(billingDateFromLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                        .addComponent(billingFromDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(billingComputerLabel)
                                    .addComponent(billingDateUntilLabel))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(billingUsernameTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(billingComputerComboBox))))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billingNameLabel)
                    .addComponent(billingNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billingComputerLabel)
                    .addComponent(billingComputerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billingDateFromLabel)
                    .addComponent(billingFromDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billingDateUntilLabel)
                    .addComponent(billingUsernameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBillingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBillingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBillingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBillingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBillingButtonActionPerformed

    private void deleteBillingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBillingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBillingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBillingButton;
    private javax.swing.JTextField billingComputerComboBox;
    private javax.swing.JLabel billingComputerLabel;
    private javax.swing.JLabel billingDateFromLabel;
    private javax.swing.JLabel billingDateUntilLabel;
    private javax.swing.JTextField billingFromDateTextField;
    private javax.swing.JLabel billingNameLabel;
    private javax.swing.JTextField billingNameTextField;
    private javax.swing.JTextField billingUsernameTextField4;
    private javax.swing.JTable billingsTable;
    private javax.swing.JButton deleteBillingButton;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
